name: rekursv
favicon: null
layout_spectrum: 0.25207
typography_spectrum: 0.24023
title: '1.6180339887'
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    feed:
      path: /rss.xml
      format: rss
      number: 10
    permalink:
      path: '/:title/'
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: UA-38493523-4
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#FFFFFF'
    - '#D0D0CE'
    - '#1E1E17'
    - '#A4A4A2'
    - '#787876'
  brandStrength: 0.1875
  lightness: 0.4178923261351883
  saturation: 0.3838395876809955
  rhythmicContrast: 0.6571195558644831
purpose: []
